/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javagradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testContarElementos() {
        int[] array = {1, 2, 3, 4, 5};
        App gestor = new App(array);
        assertEquals(5, gestor.contarElementos());
    }

    @Test
    public void testRetornarPrimer() {
        int[] array = {1, 2, 3, 4, 5};
        App gestor = new App(array);
        assertEquals(1, gestor.retornarPrimer());
    }

    @Test
    public void testRetornarDarrer() {
        int[] array = {1, 2, 3, 4, 5};
        App gestor = new App(array);
        assertEquals(5, gestor.retornarDarrer());
    }

    @Test
    public void testRetornarTercer() {
        int[] array = {1, 2, 3, 4, 5};
        App gestor = new App(array);
        assertEquals(Integer.valueOf(3), gestor.retornarTercer());
    }

    @Test
    public void testSumaElementos() {
        int[] array = {1, 2, 3, 4, 5};
        App gestor = new App(array);
        assertEquals(15, gestor.sumaElementos());
    }

    @Test
    public void testMediaElementos() {
        int[] array = {1, 2, 3, 4, 5};
        App gestor = new App(array);
        assertEquals(3.0, gestor.mediaElementos(), 0.001);
    }

    @Test
    public void testMediaElementosConArrayVacio() {
        int[] array = {};
        App gestor = new App(array);
        assertEquals(0.0, gestor.mediaElementos(), 0.001);
    }
}
