/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javagradle;

public class App {
    private int[] array;

    public App(int[] array) {
        this.array = array;
    }

    public int contarElementos() {
        int count = array.length;
        System.out.println("Numero de elementos: " + count);
        return count;
    }

    public int retornarPrimer() {
        int first = (array.length > 0) ? array[0] : 0;
        System.out.println("Primer elemento: " + first);
        return first;
    }

    public int retornarDarrer() {
        int last = (array.length > 0) ? array[array.length - 1] : 0;
        System.out.println("Ultimo elemento: " + last);
        return last;
    }

    public Integer retornarTercer() {
        Integer third = (array.length >= 3) ? array[2] : null;
        System.out.println("Tercer elemento: " + third);
        return third;
    }

    public int sumaElementos() {
        int suma = 0;
        for (int num : array) {
            suma += num;
        }
        System.out.println("Suma de elementos: " + suma);
        return suma;
    }

    public double mediaElementos() {
        double media = (array.length > 0) ? ((double) sumaElementos() / array.length) : 0;
        System.out.println("Media de elementos: " + media);
        return media;
    }
}